### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by kenmazaika** [mitchmills/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by mitchmills** [comment]
I added the following line inside the <head> section of application.html.erb:

<meta name="viewport" content="width=device-width, initial-scale=1">

Is that what you were referring to?

**Comment by kenmazaika** [comment]
Exactly.  Looks perfect.  Thumbs up! 👍
